-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS public.estados
(
    id_estado uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying COLLATE pg_catalog."default",
    CONSTRAINT estados_pkey PRIMARY KEY (id_estado)
);

CREATE TABLE IF NOT EXISTS public.solicitud
(
    id_solicitud uuid NOT NULL DEFAULT gen_random_uuid(),
    monto integer NOT NULL,
    plazo date NOT NULL,
    email character varying COLLATE pg_catalog."default",
    documento character varying COLLATE pg_catalog."default" NOT NULL,
    id_estado uuid NOT NULL,
    id_tipo_prestamo uuid NOT NULL,
    CONSTRAINT solicitud_pkey PRIMARY KEY (id_solicitud)
);

CREATE TABLE IF NOT EXISTS public.tipo_prestamo
(
    id_tipo_prestamo uuid NOT NULL DEFAULT gen_random_uuid(),
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    monto_minimo integer NOT NULL,
    monto_maximo integer NOT NULL,
    tasa_interes numeric NOT NULL,
    validacion_automatica boolean NOT NULL,
    CONSTRAINT tipo_prestamo_pkey PRIMARY KEY (id_tipo_prestamo)
);

ALTER TABLE IF EXISTS public.solicitud
    ADD CONSTRAINT id_estado FOREIGN KEY (id_estado)
    REFERENCES public.estados (id_estado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.solicitud
    ADD CONSTRAINT id_tipo_prestamo FOREIGN KEY (id_tipo_prestamo)
    REFERENCES public.tipo_prestamo (id_tipo_prestamo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;