server:
  port: 8081
spring:
  application:
    name: "Solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://solicitudes-microservice:4200,http://solicitudes-microservice:8081}
adapters:
  r2dbc:
    host: ${SOLICITUDES_DB_HOST:postgres17_db_app}
    port: ${SOLICITUDES_DB_PORT:5434}
    database: ${SOLICITUDES_DB_NAME:solicitudes}
    schema: ${SOLICITUDES_DB_SCHEMA:public}
    username: ${SOLICITUDES_DB_USER:postgres}
    password: ${SOLICITUDES_DB_PASSWORD:1234}
routes:
  paths:
    applications:
      applications: "/api/v1/solicitudes"
      calculateDebtCapacity: "/api/v1/calcular-capacidad"
    auth-microservice:
      baseUrl: ${AUTH_MICROSERVICE_BASE_URL:http://auth-microservice:8080}
      users:
        existsByDocumentAndEmail: "/api/v1/usuarios/exists"
      auth:
        isSameEmailAsToken: "/api/v1/auth/same-email"
        getRoleByAuthHeaderToken: "/api/v1/auth/role"
adapter:
  sqs:
    region: ${AWS_REGION}
    notificationQueueUrl: ${AWS_NOTIFICATION_SQS_QUEUE_URL}
    debtCapacityQueueUrl: ${AWS_DEBT_CAPACITY_SQS_QUEUE_URL}
